#!/bin/sh
#
# Build the entire project using the autogen.sh, configure, make, make install
#
# Use these script at your own risk!
# These are generally for Unix platforms.
# Start this script from the source directory.

set -e

SOURCE_PATH=`pwd`

# Create output directory
cd ..
rm -rf BUILD
mkdir -p BUILD/dist BUILD/zipios

# Run cmake
cd BUILD
BUILD_PATH=`pwd`
cd zipios
cmake -DCMAKE_INSTALL_PREFIX:PATH=$BUILD_PATH/dist \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_MODULE_PATH:PATH=$SOURCE_PATH/cmake \
          ../../zipios

# Build
make

# Install
make install

# Run tests
cd $SOURCE_PATH/tests
../../BUILD/zipios/tests/zipios_tests


# vim: ts=2 sw=2 et et
