#!/bin/sh
#
# Run the tests against an existing GNU_BUILD

set -e

# Run a build first
make -C ../BUILD/zipios

# Go in the tests directory
if test -z "$1"
then
	make -C ../BUILD/zipios run_zipios_tests
else
	echo ../BUILD/zipios/tests/zipios_tests "$*"
	../BUILD/zipios/tests/zipios_tests "$*"
fi

