#!/bin/sh
#
# Run the tests against an existing GNU_BUILD

set -e

# Run a build first
make -C ../BUILD/zipios

# Go in the tests directory
cd tests

# Run the tests
../../BUILD/zipios/tests/zipios_tests

