#!/bin/bash

set -e

if test "$1" = "--help" -o "$1" = "-h"
then
    echo "Usage: $0 [--opt]"
    echo "where --opt is one of:"
    echo "   --all          run all tests"
    echo "   --filepath     run the filepath tests"
    echo "   --full         run all tests and publish to the world"
    exit 1;
fi

if test "$1" = "--full"
then
    FULL=true
    shift
else
    FULL=false
fi

start_date=`date`
SOURCE_PATH=`pwd`
MAJOR=`grep ZIPIOS_VERSION_MAJOR CMakeLists.txt | sed -e 's/^.*set(.*ZIPIOS_VERSION_MAJOR.*\([0-9]\+\).*$/\1/'`
MINOR=`grep ZIPIOS_VERSION_MINOR CMakeLists.txt | sed -e 's/^.*set(.*ZIPIOS_VERSION_MINOR.*\([0-9]\+\).*$/\1/'`
PATCH=`grep ZIPIOS_VERSION_PATCH CMakeLists.txt | sed -e 's/^.*set(.*ZIPIOS_VERSION_PATCH.*\([0-9]\+\).*$/\1/'`
VERSION="$MAJOR.$MINOR.$PATCH"
echo "***"
echo "*** zipios coverage for version $VERSION (`date`)"
echo "***"
mkdir -p ../BUILD/zipios_coverage
rm -rf ../BUILD/zipios_coverage/*
cd ../BUILD
BUILD_PATH=`pwd`
cd zipios_coverage
# request coverage in this build
cmake -DCMAKE_INSTALL_PREFIX:PATH=$BUILD_PATH/dist \
      -DCMAKE_BUILD_TYPE=Debug \
      -Dzipios_project_COVERAGE:BOOL=ON \
      -DCMAKE_MODULE_PATH:PATH=$SOURCE_PATH/cmake \
          ../../zipios
echo
echo "***"
echo "*** compile (`date`)"
echo "***"
VERBOSE=1 make
echo
echo "***"
echo "*** run (`date`)"
echo "***"
# TODO:
# Cash does not give us such... we may want to bypass the limitation...
#if test `tests/zipios_tests --version` != "$VERSION"
#then
#    echo "the version of test_as2js (`BUILD/tests/test_as2js --version`) is not equal to the project version ($VERSION)"
#    exit 1;
#fi
if $FULL
then
    # We test the pipe status on exit to detect whether the test failed
    echo "Start running the tests on `date`" >test_log.txt
    echo >>test_log.txt
    tests/zipios_tests 2>&1 | tee -a test_log.txt; test ${PIPESTATUS[0]} -eq 0
    echo >>test_log.txt
    echo "Finished running the tests on `date`" >>test_log.txt
else
    # "brief" test while working on a specific test
    if test "$1" == "--all" -o -z "$1"
    then
        # Do it all, but not published
        tests/zipios_tests
    else
        tests/zipios_tests $1
    fi
    # just in case, remove the log file if there is one
    rm -f test_log.txt
fi
cd ..

echo
echo "***"
echo "*** gcov/lcov (`date`)"
echo "***"


# The following lcov options can be used under Ubuntu 14.04+
# Use --no-external and --base-directory $SOURCE_PATH
# to avoid /usr/include and other unwanted files
# (only available in lcov version 1.10+)
lcov --capture --no-external --directory zipios_coverage --base-directory $SOURCE_PATH --output-file coverage.info
mkdir -p zipios_coverage_html
genhtml --legend --demangle-cpp --no-branch-coverage --show-details coverage.info --output-directory zipios_coverage_html


end_date=`date`

# Statistics
echo "<html><head><title>zipios $VERSION statistics</title></head><body>" >zipios_coverage_html/statistics.html
echo "<h3>Statistics of the zipios $VERSION code</h3><pre>" >>zipios_coverage_html/statistics.html
cloc $SOURCE_PATH/src/ $SOURCE_PATH/tools/ $SOURCE_PATH/zipios++/ >>zipios_coverage_html/statistics.html
echo "</pre><h3>Statistics of the zipios $VERSION tests</h3><pre>" >>zipios_coverage_html/statistics.html
cloc $SOURCE_PATH/tests/ >>zipios_coverage_html/statistics.html
echo "</pre></body></html>" >>zipios_coverage_html/statistics.html

# Test output (Logs)
echo "<html><head><title>as2js $VERSION test logs</title></head><body><h3>Logs for the as2js $VERSION tests</h3><p>Tests started on $start_date and finished on $end_date</p><pre>" >zipios_coverage_html/test_log.html
if test -f test_log.txt
then
    # If test_log.txt does not exist, the user got the logs in the
    # console already
    cat test_log.txt >>zipios_coverage_html/test_log.html
fi
echo "</pre></body></html>" >>zipios_coverage_html/test_log.html


if test -f test_log.txt
then
    echo "***"
    echo "*** publication to ... ($end_date)"
    echo "***"

    # For publication, if that directory does not exist, you probably don't
    # have a website to display this data
    #if test -d /usr/clients/www/.../public_html
    #then
    #        cp $SOURCE_PATH/dev/index.php /usr/clients/www/.../public_html/.
    #        mkdir -p /usr/clients/www/.../public_html/zipios-$VERSION
    #        cp -r zipios_coverage_html/* /usr/clients/www/.../public_html/zipios-$VERSION/.
    #        #cp zipios_coverage_html/statistics.html /usr/clients/www/.../public_html/zipios-$VERSION/.
    #fi
fi

echo "Process started  on $start_date"
echo "Process finished on $end_date"

# vim: ts=4 sw=4 et
